[project]
name = "mech2700"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "rich",
    "scipy",
]

[project.scripts]
clean = "tools.script:clean"
code = "tools.script:code"
fmt = "tools.script:fmt"
lint = "tools.script:lint"
latex-compile = "tools.script:latex_compile"

[dependency-groups]
dev = [
    "badness==0.10.0",
    "ipykernel",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
required-version = ">=0.12.0,<0.13.0"

[tool.uv.build-backend]
module-name = "tools"
module-root = ""

[tool.ruff]
line-length = 80

[tool.ruff.lint]
extend-select = ["E501"]
